apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: postgres-dev
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    value: "host=postgresql.default.svc.cluster.local user=postgres password=postgres port=5432 connect_timeout=10 database=dapr"
scopes:
- fake-app
